# Website: https://projecteuler.net/archives
# Project Euler 
# Problem - 2

#----------------------------------------------------------------------------------------------
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.
#----------------------------------------------------------------------------------------------

import numpy as np

num_3 = 0
num_1 = 1
num_2 = 2
fibonacci_sequence = [1, 2]

while True:
    num_3 = num_1 + num_2
    if num_3 > 4e6:
        break
    num_1 = num_2
    num_2 = num_3
    
    if num_3%2==0:
        fibonacci_sequence.append(num_3)

print(fibonacci_sequence)

fibonacci_sequence_sum = np.sum(fibonacci_sequence) - 1
print(fibonacci_sequence_sum)




